import { spawn } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const HANA_DIR = '.hana'
const SCHEMA_FILE = '_schema.ts'
const CONFIG_FILE = 'drizzle.config.ts'

function detectPlugins(cwd: string): string[] {
  const pkgPath = join(cwd, 'package.json')
  if (!existsSync(pkgPath)) return []

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
  const allDeps = {
    ...pkg.dependencies,
    ...pkg.devDependencies,
  }

  return Object.keys(allDeps).filter((name) => name.startsWith('@hanano/plugin-'))
}

function loadExtraSchemas(cwd: string): string[] {
  const configPath = join(cwd, 'hana.config.ts')
  if (!existsSync(configPath)) return []

  const content = readFileSync(configPath, 'utf-8')
  const match = content.match(/extraSchemas\s*:\s*\[([^\]]*)\]/)
  if (!match) return []

  const matched = match[1] ?? ''
  return matched
    .split(',')
    .map((s) => s.trim().replace(/['"]/g, ''))
    .filter(Boolean)
}

function generateSchemaBarrel(cwd: string): string {
  const plugins = detectPlugins(cwd)
  const extraSchemas = loadExtraSchemas(cwd)

  const lines = ['// Auto-generated by hanabi CLI. Do not edit.', "export * from '@hanano/schema'"]

  for (const plugin of plugins) {
    lines.push(`export * from '${plugin}/schema'`)
  }

  for (const schemaPath of extraSchemas) {
    lines.push(`export * from '${schemaPath}'`)
  }

  return lines.join('\n')
}

function generateDrizzleConfig(): string {
  return `import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './${HANA_DIR}/${SCHEMA_FILE}',
  out: './drizzle',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
})
`
}

function ensureHanaDir(cwd: string): void {
  const dir = join(cwd, HANA_DIR)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
}

function ensureGitignore(cwd: string): void {
  const gitignorePath = join(cwd, '.gitignore')
  if (!existsSync(gitignorePath)) return

  const content = readFileSync(gitignorePath, 'utf-8')
  if (!content.includes(HANA_DIR)) {
    writeFileSync(gitignorePath, `${content.trimEnd()}\n${HANA_DIR}/\n`)
  }
}

function runDrizzleKit(cwd: string, subcommand: string): Promise<void> {
  const configPath = join(HANA_DIR, CONFIG_FILE)

  return new Promise((resolve, reject) => {
    const child = spawn('bunx', ['drizzle-kit', subcommand, '--config', configPath], {
      cwd,
      stdio: 'inherit',
      shell: true,
    })

    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`drizzle-kit ${subcommand} exited with code ${code}`))
    })

    child.on('error', reject)
  })
}

export async function runDbCommand(subcommand: string): Promise<void> {
  const validCommands = ['push', 'generate', 'migrate']
  if (!validCommands.includes(subcommand)) {
    console.error(`Unknown db subcommand: ${subcommand}`)
    console.error(`Usage: hanabi db <${validCommands.join('|')}>`)
    process.exit(1)
  }

  if (!process.env.DATABASE_URL) {
    console.error('DATABASE_URL environment variable is required.')
    process.exit(1)
  }

  const cwd = process.cwd()

  console.log('Scanning for installed plugins...')
  const plugins = detectPlugins(cwd)
  if (plugins.length > 0) {
    console.log(`Found plugins: ${plugins.join(', ')}`)
  }

  ensureHanaDir(cwd)
  ensureGitignore(cwd)

  const schemaContent = generateSchemaBarrel(cwd)
  writeFileSync(join(cwd, HANA_DIR, SCHEMA_FILE), schemaContent)

  const configContent = generateDrizzleConfig()
  writeFileSync(join(cwd, HANA_DIR, CONFIG_FILE), configContent)

  console.log(`Running drizzle-kit ${subcommand}...`)
  await runDrizzleKit(cwd, subcommand)
}
