export { default as LatestPosts } from '../public/LatestPosts.vue'
export { default as CategoriesView } from './CategoriesView.vue'
export { default as LatestPostsConfigForm } from './LatestPostsConfigForm.vue'
export { default as PostsView } from './PostsView.vue'
export { default as RecentPostsCard } from './RecentPostsCard.vue'
